#!/usr/bin/groovy
package it.sky.dp.jenkins.salesforce

class Constants {
    // TECH CONFIGS
    static final String JENKINS_SLFC_SLAVE_NODE_LABEL = "sky-cicd-prod-slsf"
    static final DEFAULT_PROJECT = "SFDC_Arcadia"
    static final MAP_KEY_PROJECT_NAME = "PROJECT_NAME"

    // INPUT PARAMETERS
    static final String MAP_KEY_JOB_NAME = "JOB_NAME"
    static final String MAP_KEY_BRANCH_NAME = "BRANCH_NAME"
    static final String MAP_KEY_START_HASH = "START_HASH"
    static final String MAP_KEY_END_HASH = "END_HASH"
    static final String MAP_KEY_VALIDATE_ONLY = "VALIDATE_ONLY"
    static final String MAP_KEY_TARGET_ENVIRONMENT = "TARGET_ENVIRONMENT"
    static final String MAP_KEY_TEST_LEVEL = "TEST_LEVEL"
    static final String MAP_KEY_WORKING_PATH = "WORKING_PATH"
    static final String MAP_KEY_SOURCE_BRANCH_NAME = "SOURCE_BRANCH_NAME"
    static final String MAP_KEY_TARGET_BRANCH_NAME = "TARGET_BRANCH_NAME"
    static final String MAP_KEY_SKIP_STORE = "SKIP_STORE"
    static final String MAP_KEY_RELEASE_VERSION = "RELEASE_VERSION"
    static final String MAP_KEY_PR_DESCRIPTION = "PR_DESCRIPTION"
    static final String MAP_KEY_SKIP_SCA = "SKIP_SCA"
    static final String MAP_KEY_AVAILABLE_PRS = "AVAILABLE_PRS"
    static final String MAP_KEY_DRY_RUN = "DRY_RUN"
    static final String MAP_KEY_BRANCH_CONFIGURATION = "BRANCH_CONFIGURATION"
    static final String MAP_KEY_ALIGNMENT_JOBS = "ALIGNMENT_JOBS"
    static final String MAP_KEY_SKIP_VALIDATE = "SKIP_VALIDATE"
    static final String MAP_KEY_QUICK_DEPLOY_ID = "QUICK_DEPLOY_ID"
    static final String MAP_KEY_BRANCHES_TO_EXCLUDE = "BRANCHES_TO_EXCLUDE"
    static final String MAP_KEY_TAGS_TO_EXCLUDE = "TAGS_TO_EXCLUDE"
    static final String MAP_KEY_NEW_BRANCH_NAME = "NEW_BRANCH_NAME"

    //introduzione nuovo parametro
    static final String MAP_KEY_SKIP_INFO_COMMIT = "SKIP_INFO_COMMIT"

    // OTHER PARAMETERS
    static final String MAP_KEY_JOB_INPUT_PARAMS = "JOB_INPUT_PARAMS"
    static final String MAP_KEY_REPOSITORY_URL = "REPOSITORY_URL"
    static final String MAP_KEY_REPOSITORY_CREDENTIAL_ID = "REPOSITORY_CREDENTIAL_ID"
    static final String MAP_KEY_GIT_LAST_TAG = "GIT_LAST_TAG"
    static final String MAP_KEY_GIT_SHA1_FROM = "GIT_SHA1_FROM"
    static final String MAP_KEY_GIT_SHA1_TO = "GIT_SHA1_TO"
    static final String MAP_KEY_GIT_SHA_BEFORE = "GIT_SHA_BEFORE"
    static final String MAP_KEY_GIT_SHA_AFTER = "GIT_SHA_AFTER"
    static final String MAP_KEY_TEST_CLASSES = "TEST_CLASSES"
    static final String MAP_KEY_MANUAL_PROCEDURES = "MANUAL_PROCEDURES"
    static final String MAP_KEY_TEST_LEVEL_VALIDATE = "TEST_LEVEL_VALIDATE"
    static final String MAP_KEY_TEST_LEVEL_DEPLOY = "TEST_LEVEL_DEPLOY"
    static final String MAP_KEY_DELTA_FORCEAPP_EXISTS = "DELTA_FORCEAPP_EXISTS"
    static final String MAP_KEY_DELTA_CLASSES_EXISTS = "DELTA_CLASSES_EXISTS"
    static final String MAP_KEY_DELTA_MANUAL_PROCEDURES_EXISTS = "DELTA_MANUAL_PROCEDURES_EXISTS"
    static final String MAP_KEY_DELTA_PRE_MANUAL_PROCEDURES_EXISTS = "DELTA_PRE_MANUAL_PROCEDURES_EXISTS"
    static final String MAP_KEY_DELTA_POST_MANUAL_PROCEDURES_EXISTS = "DELTA_POST_MANUAL_PROCEDURES_EXISTS"
    static final String MAP_KEY_MANUAL_PROCEDURES_PRE_APPROVER = "MANUAL_PROCEDURES_PRE_APPROVER"
    static final String MAP_KEY_MANUAL_PROCEDURES_POST_APPROVER = "MANUAL_PROCEDURES_POST_APPROVER"
    static final String MAP_KEY_PRE_MANUAL_PROCEDURES_LIST = "PRE_MANUAL_PROCEDURES_LIST"
    static final String MAP_KEY_POST_MANUAL_PROCEDURES_LIST = "POST_MANUAL_PROCEDURES_LIST"
    static final String MAP_KEY_DEPLOY_TAG_NAME = "DEPLOY_TAG_NAME"
    static final String MAP_KEY_NEXUS_ARTIFACT_URL = "NEXUS_ARTIFACT_URL"
    static final String MAP_KEY_BUILD_USER_ID = "BUILD_USER_ID"
    static final String MAP_KEY_BLUE_OCEAN_URL = "BLUE_OCEAN_URL"
    static final String MAP_KEY_DOCKER_IMAGE_NAME = "DOCKER_IMAGE_NAME"
    static final String MAP_KEY_DOCKER_IMAGE_TAG = "DOCKER_IMAGE_TAG"
    static final String MAP_KEY_DOCKER_IMAGE_FULLNAME = "DOCKER_IMAGE_FULLNAME"
    static final String MAP_KEY_DOCKER_REGISTRY_PROTOCOL = "DOCKER_REGISTRY_PROTOCOL"
    static final String MAP_KEY_DOCKER_REGISTRY_ACCOUNT_ID = "REGISTRY_ACCOUNT_ID"
    static final String MAP_KEY_DOCKER_REGISTRY_ENDPOINT = "DOCKER_REGISTRY_ENDPOINT"
    static final String MAP_KEY_DOCKER_REGISTRY_REGION = "DOCKER_REGISTRY_REGION"
    static final String MAP_KEY_DOCKER_BUILD_SKIP = "DOCKER_BUILD_SKIP"
    static final String MAP_KEY_DOCKER_PULL_SKIP = "DOCKER_PULL_SKIP"
    static final String MAP_KEY_DOCKERFILE_PATH = "DOCKERFILE_PATH"
    static final String MAP_KEY_SALESFORCE_VERSION = "SALESFORCE_VERSION"
    static final String MAP_KEY_SLACK_MESSAGE = "SLACK_MESSAGE"
    static final String MAP_KEY_AVAILABLE_PRS_MERGE = "AVAILABLE_PRS_MERGE"
    static final String MAP_KEY_AVAILABLE_PRS_NOMERGE = "AVAILABLE_PRS_NOMERGE"
    static final String MAP_KEY_IS_QUICK_DEPLOY = "IS_QUICK_DEPLOY"
    static final String MAP_KEY_NUMBER_PR = "NUMBER_PR"
    static final String MAP_KEY_URL_PR = "URL_PR"
    static final String MAP_KEY_ACTUAL_DEPLOY_ID = "ACTUAL_DEPLOY_ID"
    static final String MAP_KEY_UNSTABLE_MESSAGE = "MAP_KEY_UNSTABLE_MESSAGE"
    static final String MAP_KEY_MERGED_BRANCHES_TO_DELETE = "BRANCHES_TO_DELETE"
    static final String MAP_KEY_NOT_MERGED_BRANCHES_TO_DELETE = "NOT_BRANCHES_TO_DELETE"
    static final String MAP_KEY_TAGS_TO_DELETE = "TAGS_TO_DELETE"

    static final String MAP_KEY_SOURCE_ALERT_WARNING = "MAP_KEY_SOURCE_ALERT_WARNING"
    static final String MAP_KEY_SOURCE_ALERT_ERROR = "MAP_KEY_SOURCE_ALERT_ERROR"

    // vlocity
    static final String MAP_KEY_VLOCITY_ENABLED = "VLOCITY_ENABLED"
    static final String MAP_KEY_VLOCITY_GIT_LAST_TAG = "VLOCITY_GIT_LAST_TAG"
    static final String MAP_KEY_VLOCITY_GIT_SHA1_FROM = "VLOCITY_GIT_SHA1_FROM"
    static final String MAP_KEY_VLOCITY_DEPLOY_TAG_NAME = "VLOCITY_DEPLOY_TAG_NAME"
    static final String MAP_KEY_VLOCITY_DELTA_EXISTS = "VLOCITY_DELTA_EXISTS"
    static final String MAP_KEY_RELEASE_BRANCH_EXIST = "RELEASE_BRANCH_EXIST"

    static final String MAP_KEY_SF_CREDENTIALS_ID = "SF_CREDENTIALS_ID"
    static final String MAP_KEY_SLFC_URL = "SLFC_URL"

    static final String MAP_KEY_SF_CONFIGS = "SALESFORCE_CONFIGS"

    static final String SLFC_ENV_NONE = "NONE"
    static final String SLFC_ENV_PRODUCTION = "PROD"
    static final String SLFC_ENV_ACNDEVOPS = "ACNDEVOPS"
    static final String SLFC_ENV_PRODRYRUN = "PRODRYRUN"

    static final String SLFC_LOGIN_URL_TEST = "test.salesforce.com"
    static final String SLFC_LOGIN_URL_PRODUCTION = "login.salesforce.com"

    static final String TEST_RUN_LOCAL = "RunLocalTests"
    static final String TEST_RUN_NONE = "NoTestRun"
    static final String TEST_RUN_SPECIFIC = "RunSpecifiedTests"
    static final String TEST_RUN_ALL = "RunAllTestsInOrg"
    static final TEST_LEVELS = [TEST_RUN_LOCAL, TEST_RUN_NONE, TEST_RUN_SPECIFIC, TEST_RUN_ALL]

    static final String JOB_VENDOR_VALIDATE_SUFFIX = "-Validate_DEV"
    static final String JOB_CM_ACCEPTANCE_PR_SUFFIX = "-PR-Acceptance_CM"
    static final String JOB_CM_ACCEPTANCE_PR_SUFFIX_PROVA = "-PR-Acceptance_CM_PROVA"
    static final String JOB_CM_BRANCHALIGNMENT_SUFFIX = "-BranchAlignment_CM"
    static final String JOB_CM_BRANCHALIGNMENT_SUFFIX_PROVA = "-BranchAlignment_CM_PROVA"

    static final String STAGE_CLEANUP_WORKSPACE = "Cleanup workspace"
    static final String STAGE_INIT_VARIABLES = "Init variables"
    static final String STAGE_CHECKOUT_SOURCE = "Checkout source"
    static final String STAGE_PRE_DEPLOY = "Pre Deploy"
    static final String STAGE_INIT_DOCKER_IMAGE = "Init Docker Image"
    static final String STAGE_CONVERT_SOURCE = "Convert source"
    static final String STAGE_VALIDATE = "Validate"
    static final String STAGE_STORE = "Store"
    static final String STAGE_DEPLOY = "Deploy"
    static final String STAGE_TAG_SOURCE = "Tag source"

    static final String MESSAGE_OPEN_BLUE_OCEAN = "Open in Blue Ocean"
    static final String MESSAGE_DOWNLOAD_NEXUS_ARTIFACT = "Download Nexus artifact"
    static final String MESSAGE_OPEN_GIT_HUB = "Open in GitHub"

    static final String[] DEFAULT_TEST_ENVIRONMENTS = ["AM", "IT", "UAT", "TST5", "ST", "DEVE2E", "COURTESY", "PT", "CATALOG", "ACNDEVOPS"]
    static final String MAP_KEY_TEST_ENVIRONMENTS = "TEST_ENVIRONMENTS"
    static final String MAP_KEY_PROD_ENVIRONMENTS = "PROD_ENVIRONMENTS"

    static final STAGE_PRE = "PRE"
    static final STAGE_POST = "POST"

    static final MAP_KEY_ELASTICSEARCH_URL = "elasticsearchUrl"
    static final MAP_KEY_ELASTICSEARCH_MONITORING_JSON_FILE_NAME = "monitoringJsonFileName"
    static final MAP_KEY_ELASTICSEARCH_BRANCH_NAME = "branchName"
    static final MAP_KEY_ELASTICSEARCH_BUILD_USER_ID = "buildUserId"
    static final MAP_KEY_ELASTICSEARCH_RELEASE_VERSION = "releaseVersion"
    static final MAP_KEY_ELASTICSEARCH_TARGET_ENV = "targetEnv"
    static final MAP_KEY_ELASTICSEARCH_JOB_NAME = "jobName"
    static final MAP_KEY_ELASTICSEARCH_BUILD_NUMBER = "buildNumber"
    static final MAP_KEY_ELASTICSEARCH_ENVIRONMENTS = "environments"
    static final MAP_KEY_ELASTICSEARCH_INDEX_PREFIX = "indexPrefix"
}
